baseURL = "https://movietheme.muthukrishnan.dev/"

title = "movie review"

languageCode = "en-us"
summaryLength = 10
paginate = 5
copyright = "&copy; {year} {name}. All rights reserved." # {year}, {name} supported

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = false

theme = "movie-theme"

[outputFormats.SearchIndex]
baseName = "searchindex"
mediaType = "application/json"
isPlainText = true
notAlternative = true

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
